-- Script pour insérer un profil partenaire de test
-- Utilise l'ID du partenaire existant: bbfd419c-4c15-4ad6-8f34-0fad1f9092c7

INSERT INTO partner_profiles (
    user_id,
    civility,
    first_name,
    last_name,
    email,
    phone,
    birth_date,
    address,
    postal_code,
    city,
    company_name,
    legal_form,
    capital,
    company_address,
    company_postal_code,
    company_city,
    rcs,
    siren,
    representative_name,
    representative_title,
    activity_domains,
    languages,
    diplomas,
    career_paths,
    main_functions,
    professional_experiences,
    business_sectors,
    structure_types,
    current_remuneration_type,
    current_remuneration_amount,
    questionnaire_completed,
    completed_at
) VALUES (
    'bbfd419c-4c15-4ad6-8f34-0fad1f9092c7', -- ID du partenaire existant
    'M.',
    'Pat',
    'Dumoulin',
    'part@gmail.com',
    '0612345678',
    '1990-05-15',
    '123 Rue de la Paix',
    '75001',
    'Paris',
    'Entreprise Test SARL',
    'SARL',
    '100000',
    '456 Avenue des Champs',
    '75008',
    'Paris',
    'RCS Paris 123456789',
    '123456789',
    'M. Test',
    'Directeur Général',
    '["Direction Financière", "Direction Juridique"]'::jsonb,
    '["Anglais bilingue", "Allemand courant"]'::jsonb,
    '["Master Finance", "DESMA HEC"]'::jsonb,
    '["Commerce", "Finance"]'::jsonb,
    '["Président", "Directeur Général Groupe"]'::jsonb,
    '["Accompagnement Ciri", "Carve-out", "Acquisition"]'::jsonb,
    '["Finance", "Conseil"]'::jsonb,
    '["PME", "ETI"]'::jsonb,
    'daily',
    800.00,
    true,
    NOW()
) ON CONFLICT (user_id) DO UPDATE SET
    civility = EXCLUDED.civility,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    birth_date = EXCLUDED.birth_date,
    address = EXCLUDED.address,
    postal_code = EXCLUDED.postal_code,
    city = EXCLUDED.city,
    company_name = EXCLUDED.company_name,
    legal_form = EXCLUDED.legal_form,
    capital = EXCLUDED.capital,
    company_address = EXCLUDED.company_address,
    company_postal_code = EXCLUDED.company_postal_code,
    company_city = EXCLUDED.company_city,
    rcs = EXCLUDED.rcs,
    siren = EXCLUDED.siren,
    representative_name = EXCLUDED.representative_name,
    representative_title = EXCLUDED.representative_title,
    activity_domains = EXCLUDED.activity_domains,
    languages = EXCLUDED.languages,
    diplomas = EXCLUDED.diplomas,
    career_paths = EXCLUDED.career_paths,
    main_functions = EXCLUDED.main_functions,
    professional_experiences = EXCLUDED.professional_experiences,
    business_sectors = EXCLUDED.business_sectors,
    structure_types = EXCLUDED.structure_types,
    current_remuneration_type = EXCLUDED.current_remuneration_type,
    current_remuneration_amount = EXCLUDED.current_remuneration_amount,
    questionnaire_completed = EXCLUDED.questionnaire_completed,
    completed_at = EXCLUDED.completed_at,
    updated_at = NOW();

-- Vérifier l'insertion
SELECT 
    id,
    user_id,
    first_name,
    last_name,
    email,
    questionnaire_completed,
    created_at
FROM partner_profiles 
WHERE user_id = 'bbfd419c-4c15-4ad6-8f34-0fad1f9092c7';
