name: oxo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  window_manager: ^0.3.8
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  encrypt: ^5.0.3
  http: ^1.2.1
  path_provider: ^2.1.2
  package_info_plus: ^8.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/oxo_logo.png
    - assets/cleaned_image_smoothed.png
    - .env

  # Déclarez ici vos assets (images, etc.)
