name: Build and Deploy Flutter Web to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true
      
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Build Web
        run: flutter build web --web-renderer canvaskit --release --csp --dart-define=Dart2jsOptimization=O4
      
      - name: Configure environment variables for web
        run: |
          # Créer le fichier env.js avec les variables d'environnement
          echo "// Ce fichier est généré pendant le déploiement" > build/web/env.js
          echo "window.ENV = {" >> build/web/env.js
          echo "  SUPABASE_URL: \"${{ secrets.SUPABASE_URL }}\"," >> build/web/env.js
          echo "  SUPABASE_ANON_KEY: \"${{ secrets.SUPABASE_ANON_KEY }}\"" >> build/web/env.js
          echo "};" >> build/web/env.js
      
      - name: Copy .env to build folder
        run: cp .env build/web/.env
        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel
        run: |
          cd build/web
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod --yes 