name: Build and Deploy Flutter Web to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Utilisez votre version de Flutter
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Web
        run: flutter build web --web-renderer canvaskit --release --pwa-strategy offline-first
      
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel
        run: |
          cd build/web
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod --yes 