name: Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: |
          flutter pub get
          flutter doctor -v
        
      - name: Build macOS App
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          flutter build macos --release --verbose
          
      - name: Package macOS App
        run: |
          brew install create-dmg
          cd build/macos/Build/Products/Release
          create-dmg \
            --volname "OXO" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "oxo.dmg" \
            "oxo.app"
            
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/macos/Build/Products/Release/oxo.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 